# Generated by Django 4.2.4 on 2023-08-16 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_cd', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'caregiver',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_addr', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Inpatiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpatiant_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=2)),
                ('birthdate', models.CharField(max_length=20)),
                ('persnal_cd', models.CharField(max_length=50)),
                ('important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inpatiant', to='config.caregiver')),
            ],
            options={
                'db_table': 'inpatiant',
            },
        ),
        migrations.CreateModel(
            name='Voice_sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='voice_sample')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sample', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_sample',
            },
        ),
        migrations.CreateModel(
            name='Voice_cloining_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.FileField(upload_to='voice_cloining_model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_cloining_model', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_cloining_model',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to='config.caregiver')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_profile',
            },
        ),
        migrations.CreateModel(
            name='Inpatiant_children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inpatiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inpatiant_children', to='config.inpatiant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inpatiant_children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inpatiant_children',
            },
        ),
        migrations.AddField(
            model_name='caregiver',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to='config.hospital'),
        ),
    ]
