# Generated by Django 4.2.4 on 2023-09-04 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inpatiant_children',
            new_name='InpatiantChildren',
        ),
        migrations.RenameModel(
            old_name='Voice_cloining_model',
            new_name='VoiceCloiningModel',
        ),
        migrations.RenameModel(
            old_name='Voice_sample',
            new_name='VoiceSample',
        ),
        migrations.RenameField(
            model_name='inpatiant',
            old_name='birthdate',
            new_name='birth',
        ),
    ]
