# Generated by Django 4.2.4 on 2023-09-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_profile_caregiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
