# Generated by Django 4.2.4 on 2023-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_profile_training_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecloiningmodel',
            name='model_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='voicesample',
            name='file_path',
            field=models.CharField(max_length=1024),
        ),
    ]
